service: cf-language-app

plugins:
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge'
  - 'serverless-offline'

provider:
  name: aws
  stage: prod
  region: us-east-1
  profile: personal
  apiGateway:
    restApiId:
      Ref: LanguageAppApiGW
    restApiRootResourceId:
      Fn::GetAtt:
        - LanguageAppApiGW
        - RootResourceId
  deploymentBucket:
    name: serverless-deployment-bucket-illia-us-east-1
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource:
            - 'Fn::GetAtt':
                - Table
                - Arn
          Action:
            - 'dynamodb:Scan'
            - 'dynamodb:PutItem'
            - 'dynamodb:GetItem'
            - 'dynamodb:UpdateItem'

resources:
  - ${file(api-geteway/dist.yml)}
  - ${file(dynamodb/dist.yml)}

functions:
  auth:
    name: language-app-auth
    handler: api/auth/index.handler
    description: auth
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: api/auth
          method: post
          cors: true
  getTable:
    name: language-app-get-item
    handler: api/getItem/index.handler
    description: get item from the dynamodb table
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: api/getItem
          method: get
          cors: true
  postItem:
    name: language-app-post-item
    handler: api/postItem/index.handler
    description: post item to the dynamodb table
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: api/postItem
          method: post
          cors: true
  updateItem:
    name: language-app-update-item
    handler: api/updateItem/index.handler
    description: updates item attribute
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: api/updateItem
          method: post
          cors: true